### ISSUE TITLE
Atualização de cadastro do cliente

### ISSUE THREAD

**Issue by LEGAMIX** [whmcsred/Valid-Account#1]
Bom dia!

Estamos testando o addon e verifiquei um bug que impedi o cliente ou o administrador de atualizar os dados do cadastro por retornar o erro: 

> Ocorreram os seguintes erros: O CNPJ informado possui registros de conta existente em uso, entre em contato para maiores informações

> Ocorreram os seguintes erros: O CPF informado já existe conta associada, entre em contato para maiores informações

LINHA 352-401: `$existentecpf = Capsule::table('tblcustomfieldsvalues')->WHERE('fieldid', $cpfcampo)->WHERE('value', $cpf)->count();`

LINHA 390: `$existentecnpj = Capsule::table('tblcustomfieldsvalues')->WHERE('fieldid', $cnpjcampo)->WHERE('value', $cnpj)->count();`

Gostaria de apresentar uma solução simples que funcionou e que poderá ajudar outros com o mesmo problema. Basta acrescentar a instrução: `->WHERE('relid','<>', $_SESSION['uid'])`, assim será permitido a atualização do cadastro do cliente por ele ou pelo administrador.

LINHA 352-401: `$existentecpf = Capsule::table('tblcustomfieldsvalues')->WHERE('fieldid', $cpfcampo)->WHERE('value', $cpf)**->WHERE('relid','<>', $_SESSION['uid'])**->count();`

LINHA 390: `$existentecnpj = Capsule::table('tblcustomfieldsvalues')->WHERE('fieldid', $cnpjcampo)->WHERE('value', $cnpj)**->WHERE('relid','<>', $_SESSION['uid'])**->count();`

Obrigado!

**Comment by whmcsred** [comment]
Olá LEGAMIX, agradecemos a sugestão, estivemos esses dias trabalhando para trazer uma versão mais estável e com menos problemas ao usuário final, onde este mesmo problema foi relatado também, em breve a versão 1.0, estará em pleno funcionamento e disponível para download.
Mas não podemos deixar de agradecer pela sugestão, pois de breve pode ser útil a outras pessoas.
